name = "A Minecraft Modpack"
author = "ryenyuku"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20beabfc6fb4d65a637bd54b7cb95889724ba0eac0c916f60ab220b1ae88c9d3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.193"
