name = "A Minecraft Modpack"
author = "ryenyuku"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72ec64366fbba0b90ad9c25bd2276bd116e91e04c9ef246025b604857b013c19"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.193"
