name = "A Minecraft Modpack"
author = "ryenyuku"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b932184571d07920c65bd7bd98635c56ed7e258b3bc791ef7a68591694389b3a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
